title: "Daniel Mueller" # your name (or website title) here
logo: "images/Daniel Mueller Pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me
  <br>I’m a data analyst with a diverse background, open to relocation. Throughout my career, I’ve developed a strong ability to analyze client needs, create tailored solutions, and deliver insights that drive meaningful change. Now, I’m applying these skills to data analysis, specializing in transforming raw data into actionable insights with tools like Excel, Tableau, SQL, Python.<br>
  <br><br>
  <br>I’m passionate about problem-solving and data storytelling, using my creativity to build visualizations that empower organizations to make informed decisions. My unique background allows me to appreciate both the human and analytical aspects of data, providing a holistic approach to solving complex problems.<br>
  <a href="https://www.linkedin.com/in/daniel-müller-844b3b253">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/daniel.m.ller6696/vizzes">View My Tableau Projects</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: "UA-000000-0" # your Google Analytics tracking ID here
